apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: ods-monitoring-prometheus
  namespace: grafana
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: ods-monitoring-prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          <<PASTE THE TOKEN HERE>>
      type: prometheus
      url: 'https://rhods-model-monitoring.redhat-ods-monitoring.svc.cluster.local'
  name: ods-monitoring-prometheus.yaml
