apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: face-detection-model-{{ model_version }}
    serving.kserve.io/deploymentMode: ModelMesh
  name: face-detection-model-{{ model_version }}
  namespace: face-detection
  labels:
    name: face-detection-model-{{ model_version }}
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: openvino_ir
        version: opset1
      runtime: face-detection
      storage:
        key: aws-connection-minio-face-detection
        path: models/model-{{ model_version }}